---
- name: Install Zabbix Agent via Role
  hosts: all
  vars:
    zabbix_agent_version: 7.0
    zabbix_agent2: true
    zabbix_agent_hostname: "sposdk-VytunenyTunak"
    zabbix_agent_hostmetadata: "spos-vytuneny-tunak"
    zabbix_agent_server: "192.168.56.100"
    zabbix_agent_serveractive: "192.168.56.100"
    zabbix_agent_host_state: present

  tasks:
    - name: Include Zabbix Agent role
      ansible.builtin.include_role:
        name: community.zabbix.zabbix_agent
...